// Question

// Each new term in the Fibonacci sequence is generated by adding the
// previous two terms. By starting with 1 and 2, the first 10 terms will be:
//     1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
// By considering the terms in the Fibonacci sequence whose values do not
// exceed four million, find the sum of the even-valued terms.




pub fn fibonacci_sum(upper: u64) -> u64 {
    let mut first: u64 = 1;
    let mut second: u64 = 2;
    let mut sum: u64 = 0;

    while first < upper {
        if first % 2 == 0 {
            sum += first;
        }

        let temp = first;
        first = second;
        second = temp + first;
    }

    sum
}